version: '3'
services:
  app:
    image: node:6.9.5
    command: npm run debug
    volumes:
      - ./:/var/app
    working_dir: /var/app
    ports: 
      - '3000:3000'
    environment:
      PORT: 3000
